name: VaultedItemFlex
version: ${project.version}
main: net.vaultedmc.itemflex.ItemFlex
api-version: '1.21'
authors: [ VaultedMC ]
commands:
  itemflex:
    description: "Flex your items with style!"
    usage: "Usage: /itemflex"

